version: '3.1'

services:

  backend-eve:
    image: everdura/backendflask
    ports:
      - 5000:5000
    environment:
      DB_HOST: ip
      BD_PORT: 80
      DB_USER: root
      DB_PASSWORD: example

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example